import React, { createContext, useContext, useState, useEffect } from 'react';
import type { BilingualText } from '../db/mockDb';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  tText: (text: BilingualText | string | undefined | null) => string;
  isRtl: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // SaaS Landing Page
    appName: 'BistroFlow',
    appSubtitle: 'Restaurant Website Platform',
    heroTitle: 'Your Restaurant Website. Built in Minutes.',
    heroSubtitle: 'Create a professional restaurant website, manage your menu, and receive orders — without hiring a developer.',
    createWebsiteCta: 'Get Started',
    seeHowItWorks: 'View Pricing',
    howItWorksTitle: 'How It Works',
    howItWorksSubtitle: 'Launch your website in 3 simple steps.',
    step1Title: '1. Create Your Account',
    step1Desc: 'Sign up and choose the plan that fits your restaurant.',
    step2Title: '2. Add Your Menu',
    step2Desc: 'Add categories and dishes manually. Edit prices, images, and descriptions anytime.',
    step3Title: '3. Customize & Publish',
    step3Desc: 'Choose your template, brand colors, and go live in minutes.',
    featuresTitle: 'Everything You Need to Grow',
    featuresSubtitle: 'A complete platform to launch and manage your restaurant website.',
    featMenuTitle: 'Website Builder',
    featMenuDesc: 'Launch a professional restaurant website using ready-made designs.',
    featDesignTitle: 'Menu Management',
    featDesignDesc: 'Add and update your food, categories, prices and images anytime.',
    featOrderingTitle: 'Brand Customization',
    featOrderingDesc: 'Use your restaurant logo and choose your own colors.',
    featMobileTitle: 'Online Orders',
    featMobileDesc: 'Let customers order directly from your website.',
    featNoCodeTitle: 'Restaurant Dashboard',
    featNoCodeDesc: 'Manage your website, menu and orders from one place.',
    templatesTitle: 'Designed for Success',
    templatesSubtitle: 'Switch between 4 high-end layouts at any time.',
    tempModern: 'Modern Clean',
    tempLuxury: 'Premium Luxury',
    tempMinimal: 'Elegant Minimal',
    tempFastFood: 'Fast Cafe / Bistro',
    pricingTitle: 'Simple, Transparent Pricing',
    pricingSubtitle: 'One-time setup. No hidden fees. Choose the plan that fits your growth.',
    planWebsite: 'Website',
    planWebsitePrice: '$15',
    planWebsiteBilling: 'One-time payment',
    planWebsiteDesc: 'Launch a professional restaurant website with your menu.',
    planWebsiteCta: 'Get Started',
    planWebsiteFeat1: 'Professional restaurant website',
    planWebsiteFeat2: 'Choose from website templates',
    planWebsiteFeat3: 'Restaurant logo',
    planWebsiteFeat4: 'Primary and secondary colors',
    planWebsiteFeat5: 'Menu with categories',
    planWebsiteFeat6: 'Add food manually',
    planWebsiteFeat7: 'Food descriptions and prices',
    planWebsiteFeat8: 'Food images',
    planWebsiteFeat9: 'WhatsApp ordering',
    planWebsiteFeat10: 'QR code for your website/menu',
    planOrders: 'Orders',
    planOrdersPrice: '$100',
    planOrdersBilling: 'One-time setup',
    planOrdersDesc: 'Everything you need to manage your restaurant website and orders.',
    planOrdersCta: 'Start Selling',
    planOrdersFeat1: 'Everything in Website',
    planOrdersFeat2: 'Full menu management',
    planOrdersFeat3: 'Restaurant admin dashboard',
    planOrdersFeat4: 'Online ordering',
    planOrdersFeat5: 'Order management',
    planOrdersFeat6: 'Customer order information',
    planOrdersFeat7: 'Order notifications',
    planOrdersFeat8: 'Restaurant order dashboard',
    planOrdersFeat9: 'Offers/discount support',
    planOrdersFeat10: 'Website customization',
    planIntegrated: 'Integrated',
    planIntegratedPrice: '$500',
    planIntegratedBilling: 'One-time payment',
    planIntegratedDesc: 'Connect your website directly to your restaurant system and receive orders through BistroFlow.',
    planIntegratedCta: 'Choose Plan',
    planIntegratedFeat1: 'Everything in Orders',
    planIntegratedFeat2: 'Restaurant system/POS integration',
    planIntegratedFeat3: 'Orders directly through the website',
    planIntegratedFeat4: 'No WhatsApp-only ordering',
    planIntegratedFeat5: 'Advanced order management',
    planIntegratedFeat6: 'Integration setup',
    planIntegratedFeat7: 'Advanced restaurant controls',
    mostPopular: 'Most Popular',
    hostingNote: 'Hosting is billed separately as a recurring infrastructure cost.',
    faqTitle: 'Frequently Asked Questions',
    faqQ1: 'Do I need developer skills to use this?',
    faqA1: 'No. You just upload your logo, fill in your details, add your menu, and the website generates automatically. You can edit it easily in your dashboard.',
    faqQ2: 'Can customers order directly from my website?',
    faqA2: 'Yes, with the Orders plan, customers can add items to their cart, select pickup/delivery, and checkout. The order goes to your dashboard and WhatsApp.',
    faqQ3: 'How do I add my menu?',
    faqA3: 'Simply add categories and dishes manually from your dashboard. You can edit prices, images, and descriptions anytime.',
    faqQ4: 'Can I switch templates later?',
    faqA4: 'Yes. You can switch between Modern, Luxury, Minimal, and Fast Food layouts with one click without losing any data or colors.',
    ctaFooterTitle: 'Ready to Launch Your Website?',
    ctaFooterSubtitle: 'Join hundreds of restaurants growing their sales with BistroFlow.',
    footerCopyright: '© 2026 BistroFlow. All rights reserved.',
    navProduct: 'Product',
    navFeatures: 'Features',
    navPricing: 'Pricing',
    navHowItWorks: 'How it works',
    navFaq: 'FAQ',
    loginBtn: 'Log in',
    signupBtn: 'Get Started',
    heroBadge: 'Restaurant Website Platform',
    heroPrimaryCta: 'Get Started',
    heroSecondaryCta: 'View Pricing',
    featureBuilderTitle: 'Website Builder',
    featureBuilderDesc: 'Launch a professional restaurant website using ready-made designs.',
    featureMenuTitle: 'Menu Management',
    featureMenuDesc: 'Add and update your food, categories, prices and images anytime.',
    featureBrandTitle: 'Brand Customization',
    featureBrandDesc: 'Use your restaurant logo and choose your own colors.',
    featureOrdersTitle: 'Online Orders',
    featureOrdersDesc: 'Let customers order directly from your website.',
    featureDashboardTitle: 'Restaurant Dashboard',
    featureDashboardDesc: 'Manage your website, menu and orders from one place.',
    pricingBadge: 'Pricing',
    pricingNote: 'One-time setup. No subscription required.',
    faqSubtitle: 'Frequently asked questions about setup and deployment.',
    footerPrivacy: 'Privacy Policy',
    footerTerms: 'Terms of Service',
    footerContact: 'Contact',

    // Auth
    loginTitle: 'Sign In to BistroFlow',
    loginSubtitle: 'Manage your restaurant website and orders',
    signupTitle: 'Create Owner Account',
    signupSubtitle: 'Start building your website for free',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    restaurantNameLabel: 'Restaurant Name (English)',
    restaurantNameArLabel: 'Restaurant Name (Arabic)',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    invalidLogin: 'Invalid email address. Try owner@bistroflow.com or burger@bistroflow.com',

    // Onboarding
    onboardingTitle: 'Let\'s Set Up Your Restaurant',
    onboardingStep1: 'Info',
    onboardingStep2: 'Logo',
    onboardingStep3: 'Menu',
    onboardingStep4: 'Customize',
    nextBtn: 'Next Step',
    backBtn: 'Back',
    finishBtn: 'Complete Setup & Go to Dashboard',

    stepInfoTitle: 'Restaurant Information',
    stepInfoSubtitle: 'Introduce your restaurant to customers in both English & Arabic.',
    nameEnLabel: 'Restaurant Name (EN)',
    nameArLabel: 'Restaurant Name (AR)',
    descEnLabel: 'Description (EN)',
    descArLabel: 'Description (AR)',
    phoneLabel: 'Phone Number',
    addressEnLabel: 'Address (EN)',
    addressArLabel: 'Address (AR)',
    mapsLabel: 'Google Maps Link',
    hoursEnLabel: 'Opening Hours (EN)',
    hoursArLabel: 'Opening Hours (AR)',
    whatsappLabel: 'WhatsApp Order Number (with country code, e.g., 201001234567)',

    stepLogoTitle: 'Brand Identity',
    stepLogoSubtitle: 'Upload your logo to style your website and invoices.',
    uploadLogoLabel: 'Upload Logo Image',
    uploadLogoDesc: 'PNG or JPG. Max 2MB.',
    logoPreview: 'Logo Preview',

    stepMenuTitle: 'Menu Import',
    stepMenuSubtitle: 'Upload your current menu file. Our AI will convert it into a structured website menu.',
    menuUploadType: 'Choose Upload Format',
    uploadPdfBtn: 'PDF Document',
    uploadCsvBtn: 'Excel / CSV Sheet',
    uploadImgBtn: 'Menu Image/Photo',
    selectSampleBtn: 'Load Sample Menu File',
    aiRunning: 'AI is analyzing your menu...',
    aiStep1: 'Reading document text (OCR)...',
    aiStep2: 'Parsing categories and dishes...',
    aiStep3: 'Identifying prices, variants, and addons...',
    reviewMenuTitle: 'Review Extracted Menu',
    reviewMenuSubtitle: 'Verify and edit the AI-extracted categories and items before importing.',
    addCategory: 'Add Category',
    addItem: 'Add Item',
    saveImportBtn: 'Import Verified Menu',

    // Dashboard
    dashOverview: 'Overview',
    dashMenu: 'Menu Editor',
    dashDesign: 'Layouts',
    dashBranding: 'Branding & Theme',
    dashOrders: 'Incoming Orders',
    dashInfo: 'Store Profile',
    dashSettings: 'Settings',
    logoutBtn: 'Logout',

    welcomeOwner: 'Welcome Back,',
    websiteStatus: 'Website Status',
    liveSite: 'Live Website',
    draftSite: 'Unpublished Draft',
    menuSummary: 'Menu Summary',
    itemsCount: 'Dishes Total',
    categoriesCount: 'Categories Total',
    recentOrders: 'Recent Orders',
    noOrders: 'No orders received yet.',
    viewDetails: 'Details',
    statusPending: 'Pending',
    statusPreparing: 'Preparing',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
    qrCodeTitle: 'Your Website QR Code',
    qrCodeDesc: 'Download and print this QR code on tables or flyers so customers can scan and view your menu.',
    downloadQr: 'Download QR Code',

    // Menu Editor
    categoryNameEn: 'Category Name (EN)',
    categoryNameAr: 'Category Name (AR)',
    itemNameEn: 'Dish Name (EN)',
    itemNameAr: 'Dish Name (AR)',
    itemDescEn: 'Description (EN)',
    itemDescAr: 'Description (AR)',
    itemPrice: 'Price',
    itemImage: 'Image URL',
    isAvailableLabel: 'Available',
    isHiddenLabel: 'Hidden',
    saveChanges: 'Save Changes',
    publishBtn: 'Publish to Live Site',
    publishSuccess: 'Website published successfully!',

    // Branding
    colorPaletteTitle: 'Brand Color Palette',
    colorPrimary: 'Primary Theme Color',
    colorSecondary: 'Secondary Accent',
    colorBackground: 'Website Background',
    colorButton: 'Button Color',
    colorText: 'Body Text Color',
    fontLabel: 'Typography Style',
    aiColorBtn: 'AI Generate Brand Colors',
    aiColorSuccess: 'Brand colors successfully extracted from logo!',

    // Orders Panel
    orderId: 'Order ID',
    customer: 'Customer',
    orderTypeLabel: 'Type',
    orderDate: 'Date',
    totalPriceLabel: 'Total',
    orderActions: 'Actions',
    acceptOrder: 'Accept & Prepare',
    completeOrder: 'Mark Completed',
    cancelOrder: 'Cancel Order',
    pickup: 'Pickup',
    delivery: 'Delivery',
    notesLabel: 'Notes',

    // Settings
    domainSettings: 'Domain Settings',
    customDomainLabel: 'Your Subdomain / URL slug',
    pricingPlanLabel: 'Billing Plan',
    changePlan: 'Upgrade/Downgrade Plan',
    saveSettings: 'Save Settings',

    // Customer Site
    backToHome: 'Back to Home',
    aboutUs: 'About Us',
    ourMenu: 'Our Menu',
    contactUs: 'Contact Us',
    addToCart: 'Add to Cart',
    optionsTitle: 'Choose Options',
    addonsTitle: 'Add Extras',
    cartTitle: 'Shopping Cart',
    cartEmpty: 'Your cart is empty',
    quantity: 'Quantity',
    subtotal: 'Subtotal',
    checkoutTitle: 'Checkout Details',
    nameField: 'Your Name',
    phoneField: 'Phone Number',
    addressField: 'Delivery Address',
    deliveryMethod: 'Order Method',
    submitOrderWhatsApp: 'Order via WhatsApp',
    submitOrderLocal: 'Submit Order to Dashboard',
    orderSuccessTitle: 'Order Placed!',
    orderSuccessDesc: 'Your order has been sent to the restaurant. They will contact you shortly.',
    currency: 'EGP',
    whatsappMessageSent: 'Order link generated! Click to send via WhatsApp.'
  },
  ar: {
    // SaaS Landing Page
    appName: 'بيستروفلو',
    appSubtitle: 'نظام إنشاء مواقع المطاعم',
    heroTitle: 'موقع مطعمك. يُبنى في دقائق.',
    heroSubtitle: 'أنشئ موقع مطعم احترافي، أدر قائمتك، واستقبل الطلبات — دون الحاجة لتوظيف مطور.',
    createWebsiteCta: 'ابدأ الآن',
    seeHowItWorks: 'عرض الأسعار',
    howItWorksTitle: 'كيف يعمل بيستروفلو؟',
    howItWorksSubtitle: 'أطلق موقعك الإلكتروني بثلاث خطوات بسيطة فقط.',
    step1Title: '١. أنشئ حسابك',
    step1Desc: 'سجل واختر الباقة المناسبة لمطعمك.',
    step2Title: '٢. أضف قائمتك',
    step2Desc: 'أضف الفئات والأطباق يدوياً. عدّل الأسعار والصور والأوصاف في أي وقت.',
    step3Title: '٣. خصص وانشر',
    step3Desc: 'اختر قالبك وألوان علامتك التجارية وانطلق في دقائق.',
    featuresTitle: 'كل ما تحتاجه للنمو',
    featuresSubtitle: 'منصة متكاملة لإطلاق وإدارة موقع مطعمك.',
    featMenuTitle: 'منشئ المواقع',
    featMenuDesc: 'أطلق موقع مطعم احترافي باستخدام تصاميم جاهزة.',
    featDesignTitle: 'إدارة القائمة',
    featDesignDesc: 'أضف وحدّث أطباقك وفئاتك وأسعارك وصورك في أي وقت.',
    featOrderingTitle: 'تخصيص العلامة التجارية',
    featOrderingDesc: 'استخدم شعار مطعمك واختر ألوانك الخاصة.',
    featMobileTitle: 'الطلبات عبر الإنترنت',
    featMobileDesc: 'دع العملاء يطلبون مباشرة من موقعك.',
    featNoCodeTitle: 'لوحة تحكم المطعم',
    featNoCodeDesc: 'أدر موقعك وقائمتك وطلباتك من مكان واحد.',
    templatesTitle: 'تصاميم مصممة للنجاح',
    templatesSubtitle: 'تنقل بين ٤ تصاميم ومخططات مختلفة في أي وقت بنقرة واحدة.',
    tempModern: 'عصري ونظيف',
    tempLuxury: 'فاخر وراقٍ',
    tempMinimal: 'بسيط وأنيق',
    tempFastFood: 'بيسترو سريع / كافيه',
    pricingTitle: 'أسعار بسيطة وشفافة',
    pricingSubtitle: 'دفع لمرة واحدة. بدون رسوم خفية. اختر الباقة المناسبة لنمو مطعمك.',
    planWebsite: 'الموقع',
    planWebsitePrice: '١٥$',
    planWebsiteBilling: 'دفع لمرة واحدة',
    planWebsiteDesc: 'أطلق موقع مطعم احترافي مع قائمتك.',
    planWebsiteCta: 'ابدأ الآن',
    planWebsiteFeat1: 'موقع مطعم احترافي',
    planWebsiteFeat2: 'اختر من قوالب المواقع',
    planWebsiteFeat3: 'شعار المطعم',
    planWebsiteFeat4: 'الألوان الأساسية والثانوية',
    planWebsiteFeat5: 'قائمة مع فئات',
    planWebsiteFeat6: 'إضافة الطعام يدوياً',
    planWebsiteFeat7: 'أوصاف وأسعار الطعام',
    planWebsiteFeat8: 'صور الطعام',
    planWebsiteFeat9: 'الطلب عبر واتساب',
    planWebsiteFeat10: 'رمز QR لموقعك/قائمتك',
    planOrders: 'الطلبات',
    planOrdersPrice: '١٠٠$',
    planOrdersBilling: 'إعداد لمرة واحدة',
    planOrdersDesc: 'كل ما تحتاجه لإدارة موقع مطعمك وطلباتك.',
    planOrdersCta: 'ابدأ البيع',
    planOrdersFeat1: 'كل ميزات الموقع',
    planOrdersFeat2: 'إدارة قائمة كاملة',
    planOrdersFeat3: 'لوحة تحكم إدارية للمطعم',
    planOrdersFeat4: 'الطلب عبر الإنترنت',
    planOrdersFeat5: 'إدارة الطلبات',
    planOrdersFeat6: 'معلومات الطلب من العميل',
    planOrdersFeat7: 'إشعارات الطلبات',
    planOrdersFeat8: 'لوحة طلبات المطعم',
    planOrdersFeat9: 'دعم العروض والخصومات',
    planOrdersFeat10: 'تخصيص الموقع',
    planIntegrated: 'المتكامل',
    planIntegratedPrice: '٥٠٠$',
    planIntegratedBilling: 'دفع لمرة واحدة',
    planIntegratedDesc: 'اربط موقعك مباشرة بنظام مطعمك واستقبل الطلبات عبر بيستروفلو.',
    planIntegratedCta: 'اختر الباقة',
    planIntegratedFeat1: 'كل ميزات الطلبات',
    planIntegratedFeat2: 'تكامل نظام المطعم/POS',
    planIntegratedFeat3: 'طلبات مباشرة عبر الموقع',
    planIntegratedFeat4: 'بدون طلب عبر واتساب فقط',
    planIntegratedFeat5: 'إدارة طلبات متقدمة',
    planIntegratedFeat6: 'إعداد التكامل',
    planIntegratedFeat7: 'تحكم متقدم بالمطعم',
    mostPopular: 'الأكثر شيوعاً',
    hostingNote: 'الاستضافة تُدفع بشكل منفصل كتكلفة بنية تحتية متكررة.',
    faqTitle: 'الأسئلة الشائعة',
    faqQ1: 'هل أحتاج إلى خبرة برمجية لاستخدام المنصة؟',
    faqA1: 'بالتأكيد لا. كل ما عليك فعله هو رفع شعارك، ملء تفاصيل مطعمك، وإضافة قائمتك وسيقوم النظام بتوليد موقعك. يمكنك تعديل كل شيء لاحقاً من لوحة التحكم.',
    faqQ2: 'هل يمكن للزبائن الطلب مباشرة من موقعي؟',
    faqA2: 'نعم، مع باقة الطلبات، يمكن للزبائن تصفح المنيو، إضافة الأطباق للسلة، واختيار التوصيل أو الاستلام. ستصلك الطلبات في لوحة التحكم وعبر واتساب.',
    faqQ3: 'كيف أضيف قائمتي؟',
    faqA3: 'ببساطة أضف الفئات والأطباق يدوياً من لوحة التحكم. يمكنك تعديل الأسعار والصور والأوصاف في أي وقت.',
    faqQ4: 'هل يمكنني تغيير قالب الموقع لاحقاً؟',
    faqA4: 'نعم. يمكنك التبديل بين التصاميم الأربعة بنقرة زر واحدة في أي وقت دون أن تفقد أياً من بياناتك أو ألوانك الخاصة.',
    ctaFooterTitle: 'جاهز لإطلاق موقع مطعمك؟',
    ctaFooterSubtitle: 'انضم إلى مئات المطاعم التي تزيد مبيعاتها مع بيستروفلو.',
    footerCopyright: '© ٢٠٢٦ بيستروفلو. جميع الحقوق محفوظة.',
    navProduct: 'المنتج',
    navFeatures: 'الميزات',
    navPricing: 'الأسعار',
    navHowItWorks: 'كيف يعمل',
    navFaq: 'الأسئلة الشائعة',
    loginBtn: 'تسجيل الدخول',
    signupBtn: 'ابدأ الآن',
    heroBadge: 'منصة مواقع المطاعم',
    heroPrimaryCta: 'ابدأ الآن',
    heroSecondaryCta: 'عرض الأسعار',
    featureBuilderTitle: 'منشئ المواقع',
    featureBuilderDesc: 'أطلق موقع مطعم احترافي باستخدام تصاميم جاهزة.',
    featureMenuTitle: 'إدارة القائمة',
    featureMenuDesc: 'أضف وحدّث أطباقك وفئاتك وأسعارك وصورك في أي وقت.',
    featureBrandTitle: 'تخصيص العلامة التجارية',
    featureBrandDesc: 'استخدم شعار مطعمك واختر ألوانك الخاصة.',
    featureOrdersTitle: 'الطلبات عبر الإنترنت',
    featureOrdersDesc: 'دع العملاء يطلبون مباشرة من موقعك.',
    featureDashboardTitle: 'لوحة تحكم المطعم',
    featureDashboardDesc: 'أدر موقعك وقائمتك وطلباتك من مكان واحد.',
    pricingBadge: 'الأسعار',
    pricingNote: 'دفع لمرة واحدة. بدون اشتراك.',
    faqSubtitle: 'أسئلة شائعة حول الإعداد والنشر.',
    footerPrivacy: 'سياسة الخصوصية',
    footerTerms: 'شروط الخدمة',
    footerContact: 'اتصل بنا',

    // Auth
    loginTitle: 'تسجيل الدخول إلى بيستروفلو',
    loginSubtitle: 'إدارة موقع مطعمك واستقبال الطلبات',
    signupTitle: 'إنشاء حساب مالك جديد',
    signupSubtitle: 'ابدأ في بناء موقع مطعمك مجاناً',
    emailLabel: 'البريد الإلكتروني',
    passwordLabel: 'كلمة المرور',
    restaurantNameLabel: 'اسم المطعم (بالإنجليزية)',
    restaurantNameArLabel: 'اسم المطعم (بالعربية)',
    noAccount: 'ليس لديك حساب؟',
    hasAccount: 'لديك حساب بالفعل؟',
    invalidLogin: 'البريد الإلكتروني غير صحيح. جرب owner@bistroflow.com أو burger@bistroflow.com',

    // Onboarding
    onboardingTitle: 'لنبدأ في إعداد مطعمك',
    onboardingStep1: 'المعلومات',
    onboardingStep2: 'الشعار',
    onboardingStep3: 'المنيو',
    onboardingStep4: 'التخصيص',
    nextBtn: 'الخطوة التالية',
    backBtn: 'السابق',
    finishBtn: 'إكمال الإعداد والذهاب للوحة التحكم',

    stepInfoTitle: 'معلومات المطعم',
    stepInfoSubtitle: 'عرّف العملاء بمطعمك باللغتين العربية والإنجليزية.',
    nameEnLabel: 'اسم المطعم (EN)',
    nameArLabel: 'اسم المطعم (AR)',
    descEnLabel: 'الوصف (EN)',
    descArLabel: 'الوصف (AR)',
    phoneLabel: 'رقم الهاتف',
    addressEnLabel: 'العنوان (EN)',
    addressArLabel: 'العنوان (AR)',
    mapsLabel: 'رابط خرائط جوجل',
    hoursEnLabel: 'ساعات العمل (EN)',
    hoursArLabel: 'ساعات العمل (AR)',
    whatsappLabel: 'رقم واتساب لاستقبال الطلبات (مع رمز الدولة، مثلاً 201001234567)',

    stepLogoTitle: 'الهوية البصرية للمطعم',
    stepLogoSubtitle: 'رفع شعار المطعم لتخصيص موقعك وفواتيرك.',
    uploadLogoLabel: 'رفع صورة الشعار',
    uploadLogoDesc: 'PNG أو JPG. الحجم الأقصى ٢ ميجابايت.',
    logoPreview: 'معاينة الشعار',

    stepMenuTitle: 'استيراد قائمة الطعام (المنيو)',
    stepMenuSubtitle: 'ارفع ملف المنيو الحالي وسيقوم الذكاء الاصطناعي بتحويله لقائمة تفاعلية على موقعك.',
    menuUploadType: 'اختر صيغة الملف',
    uploadPdfBtn: 'ملف PDF',
    uploadCsvBtn: 'جدول إكسل / CSV',
    uploadImgBtn: 'صورة المنيو',
    selectSampleBtn: 'تحميل ملف منيو تجريبي',
    aiRunning: 'يقوم الذكاء الاصطناعي بتحليل المنيو...',
    aiStep1: 'قراءة النصوص من الملف (OCR)...',
    aiStep2: 'استخراج فئات الأطباق والوجبات...',
    aiStep3: 'تحديد الأسعار والخيارات والإضافات...',
    reviewMenuTitle: 'مراجعة المنيو المستخرج',
    reviewMenuSubtitle: 'تحقق من الأطباق والفئات وعدل عليها قبل حفظها واستيرادها.',
    addCategory: 'إضافة فئة',
    addItem: 'إضافة طبق',
    saveImportBtn: 'استيراد وتأكيد المنيو',

    // Dashboard
    dashOverview: 'نظرة عامة',
    dashMenu: 'محرر المنيو',
    dashDesign: 'القوالب والتصميم',
    dashBranding: 'الألوان والهوية',
    dashOrders: 'الطلبات الواردة',
    dashInfo: 'معلومات المطعم',
    dashSettings: 'الإعدادات',
    logoutBtn: 'تسجيل الخروج',

    welcomeOwner: 'مرحباً بك مجدداً،',
    websiteStatus: 'حالة الموقع',
    liveSite: 'الموقع منشور ولايف',
    draftSite: 'مسودة غير منشورة',
    menuSummary: 'ملخص قائمة الطعام',
    itemsCount: 'إجمالي الأطباق',
    categoriesCount: 'إجمالي الفئات',
    recentOrders: 'آخر الطلبات',
    noOrders: 'لا توجد طلبات واردة بعد.',
    viewDetails: 'التفاصيل',
    statusPending: 'قيد الانتظار',
    statusPreparing: 'جاري التحضير',
    statusCompleted: 'مكتمل',
    statusCancelled: 'ملغي',
    qrCodeTitle: 'الرمز السريع للموقع QR Code',
    qrCodeDesc: 'قم بتحميل وطباعة هذا الرمز على الطاولات أو المنشورات ليتمكن العملاء من مسحه وتصفح المنيو فوراً.',
    downloadQr: 'تحميل الرمز QR',

    // Menu Editor
    categoryNameEn: 'اسم الفئة (EN)',
    categoryNameAr: 'اسم الفئة (AR)',
    itemNameEn: 'اسم الطبق (EN)',
    itemNameAr: 'اسم الطبق (AR)',
    itemDescEn: 'وصف الطبق (EN)',
    itemDescAr: 'وصف الطبق (AR)',
    itemPrice: 'السعر',
    itemImage: 'رابط الصورة',
    isAvailableLabel: 'متوفر',
    isHiddenLabel: 'مخفي',
    saveChanges: 'حفظ التعديلات',
    publishBtn: 'نشر التغييرات للموقع لايف',
    publishSuccess: 'تم نشر الموقع بنجاح وبثه لايف!',

    // Branding
    colorPaletteTitle: 'الألوان والهوية البصرية',
    colorPrimary: 'اللون الرئيسي للموقع',
    colorSecondary: 'اللون الثانوي',
    colorBackground: 'لون الخلفية',
    colorButton: 'لون الأزرار',
    colorText: 'لون النصوص الأساسية',
    fontLabel: 'خط الموقع',
    aiColorBtn: 'توليد ألوان الهوية بالذكاء الاصطناعي',
    aiColorSuccess: 'تم استخراج ألوان علامتك التجارية من الشعار بنجاح!',

    // Orders Panel
    orderId: 'رقم الطلب',
    customer: 'العميل',
    orderTypeLabel: 'النوع',
    orderDate: 'التاريخ',
    totalPriceLabel: 'الإجمالي',
    orderActions: 'الإجراءات',
    acceptOrder: 'قبول وتحضير',
    completeOrder: 'تحديد كمكتمل',
    cancelOrder: 'إلغاء الطلب',
    pickup: 'استلام من المطعم',
    delivery: 'توصيل للمنزل',
    notesLabel: 'ملاحظات',

    // Settings
    domainSettings: 'إعدادات النطاق (الدومين)',
    customDomainLabel: 'رابط موقعك الفرعي (Subdomain)',
    pricingPlanLabel: 'باقة الاشتراك الحالية',
    changePlan: 'ترقية/تعديل الباقة',
    saveSettings: 'حفظ الإعدادات',

    // Customer Site
    backToHome: 'العودة للرئيسية',
    aboutUs: 'من نحن',
    ourMenu: 'قائمة طعامنا',
    contactUs: 'اتصل بنا',
    addToCart: 'أضف للسلة',
    optionsTitle: 'اختر الخيارات',
    addonsTitle: 'إضافات اختيارية',
    cartTitle: 'سلة المشتريات',
    cartEmpty: 'السلة فارغة حالياً',
    quantity: 'الكمية',
    subtotal: 'المجموع الفرعي',
    checkoutTitle: 'تفاصيل إتمام الطلب',
    nameField: 'اسمك الكريم',
    phoneField: 'رقم الجوال',
    addressField: 'عنوان التوصيل بالتفصيل',
    deliveryMethod: 'طريقة الاستلام',
    submitOrderWhatsApp: 'إرسال الطلب عبر الواتساب',
    submitOrderLocal: 'إرسال الطلب للمطعم مباشرة',
    orderSuccessTitle: 'تم إرسال طلبك بنجاح!',
    orderSuccessDesc: 'تم إرسال تفاصيل طلبك للمطعم بنجاح، وسيتواصلون معك قريباً لتأكيده.',
    currency: 'ج.م',
    whatsappMessageSent: 'تم توليد رابط الطلب! انقر لإرساله عبر واتساب.'
  }
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('bistroflow_lang') as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('bistroflow_lang', lang);
  };

  useEffect(() => {
    const isRtl = language === 'ar';
    document.documentElement.dir = isRtl ? 'rtl' : 'ltr';
    document.documentElement.lang = language;

    // Handle specific fonts on body
    if (isRtl) {
      document.body.style.fontFamily = "'Cairo', 'Tajawal', sans-serif";
    } else {
      document.body.style.fontFamily = "'Outfit', 'Inter', sans-serif";
    }
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const tText = (text: BilingualText | string | undefined | null): string => {
    if (!text) return '';
    if (typeof text === 'string') return text;
    return text[language] || text['en'] || '';
  };

  const isRtl = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tText, isRtl }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};